### ISSUE TITLE
Index out of range error when running cb0t (cache.dat)

### ISSUE THREAD

**Issue by shaunweavers** [AresChat/cb0t#12]
I get this error when running Cb0t
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at cb0t.UdpPacketReader.ReadByte()
   at cb0t.ChannelListPanel.LoadCache()
   at cb0t.ChannelListPanel.Create()
   at cb0t.Form1.Form1_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at cb0t.Form1.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by hollow87** [comment]
This issue seems to be from a corrupted cache.dat file
Please try deleting the file `%localappdata%\cb0tv3\data\cache.dat`
Then please let me know if that solves the issue.

**Comment by shaunweavers** [comment]
Deleting the cache.dat file resolved the issue

**Comment by hollow87** [comment]
All right thanks, I'll make a fix for it in next version.
