### ISSUE TITLE
cbot suddenly wont load chat window or userlist

### ISSUE THREAD

**Issue by itsjustmememe** [AresChat/cb0t#16]
when cbot starts i get this:
Object reference not set to an instance of an object.

   at cb0t.Room.Release()
   at cb0t.Form1.CloseChannel(Object sender, EventArgs e)
   at cb0t.RoomPanel.toolStripButton1_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
it'll load the rooms list but not the chat window or user list

**Comment by hollow87** [comment]
Does it happen upon load or does it happen when you join a room?
Also please use a more descriptive summary for the issue title.

**Comment by itsjustmememe** [comment]
it happens upon loading
